export const COLOMBIA_STATES = [
    { label: 'Amazonas', value: 'amazonas' },
    { label: 'Antioquia', value: 'antioquia' },
    { label: 'Arauca', value: 'arauca' },
    { label: 'Atlántico', value: 'atlantico' },
    { label: 'Bogota Distrito Capital', value: 'bogota' },
    { label: 'Bolívar', value: 'bolivar' },
    { label: 'Boyacá', value: 'boyaca' },
    { label: 'Caldas', value: 'caldas' },
    { label: 'Caquetá', value: 'caqueta' },
    { label: 'Casanare', value: 'casanare' },
    { label: 'Cauca', value: 'cauca' },
    { label: 'Cesar', value: 'cesar' },
    { label: 'Chocó', value: 'choco' },
    { label: 'Córdoba', value: 'cordoba' },
    { label: 'Cundinamarca', value: 'cundinamarca' },
    { label: 'Guainía', value: 'guainia' },
    { label: 'Guaviare', value: 'guaviare' },
    { label: 'Huila', value: 'huila' },
    { label: 'La Guajira', value: 'guajira' },
    { label: 'Magdalena', value: 'magdalena' },
    { label: 'Meta', value: 'meta' },
    { label: 'Nariño', value: 'narino' },
    { label: 'Norte de Santander', value: 'norte-santander' },
    { label: 'Putumayo', value: 'putumayo' },
    { label: 'Quindío', value: 'quindio' },
    { label: 'Risaralda', value: 'risaralda' },
    { label: 'Santander', value: 'santander' },
    { label: 'Sucre', value: 'sucre' },
    { label: 'Tolima', value: 'tolima' },
    { label: 'Valle del Cauca', value: 'valle' },
    { label: 'Vaupés', value: 'vaupes' },
    { label: 'Vichada', value: 'vichada' },
];
